name = "StatsDataBase"
uuid = "d398c129-eeec-4507-8021-05e78156120a"
authors = ["Kun Chen", "Daniel Cerkoney"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
